trigger:
  branches:
    include:
      - main
  paths:
    include:
      - vote/*

variables:
  - group: voting-app-var-group


pool:
  name: OCIPool

stages:
  - stage: BuildDockerImage
    displayName: Build Docker Image Stage
    jobs:
      - job: BuildDockerImageJob
        displayName: Build Docker Image Job
        steps:
        - task: Docker@2
          displayName: Build Docker Image Task
          inputs:
            containerRegistry: 'ahmedavid-docker-registry'
            repository: 'ahmedavid/voting-vote'
            command: 'build'
            Dockerfile: '**/vote/Dockerfile'
            tags: |
              $(Build.BuildId)
              latest
        - task: Docker@2
          displayName: Push Docker Image Task
          inputs:
            containerRegistry: 'ahmedavid-docker-registry'
            repository: 'ahmedavid/voting-vote'
            command: 'push'
            Dockerfile: '**/vote/Dockerfile'
            tags: |
              $(Build.BuildId)
              latest

  - stage: UpdateImages
    displayName: Update GitOps Images
    jobs:
      - job:
        steps:
        - task: ShellScript@2
          inputs:
            scriptPath: 'infra/scripts/updateK8sManifests.sh'
            args: 'vote ahmedavid/voting-vote $(Build.BuildId) $(ACCESS_TOKEN)'


