trigger:
  branches:
    include:
      - main
  paths:
    include:
      - worker/*

pool:
  name: OCIPool

stages:
  - stage: BuildDockerImage
    displayName: Build Docker Image Stage
    jobs:
      - job: BuildDockerImageJob
        displayName: Build Docker Image Job
        steps:
        - task: Docker@2
          displayName: Build Docker Image Task
          inputs:
            containerRegistry: 'ahmedavid-docker-registry'
            repository: 'ahmedavid/voting-worker'
            command: 'build'
            Dockerfile: '**/worker/Dockerfile'
            tags: |
              $(Build.BuildId)
              latest
        - task: Docker@2
          displayName: Push Docker Image Task
          inputs:
            containerRegistry: 'ahmedavid-docker-registry'
            repository: 'ahmedavid/voting-worker'
            command: 'push'
            Dockerfile: '**/worker/Dockerfile'
            tags: |
              $(Build.BuildId)
              latest
