apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-depl
  name: vote-depl
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
        - image: ahmedavid/voting-vote:2115
          imagePullPolicy: Always
          name: vote-container
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
