apiVersion: v1
kind: Service
metadata:
  name: vote-depl-svc
  namespace: voting-app
spec:
  type: ClusterIP
  selector:
    app: vote-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-ingress
  namespace: voting-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: vote.test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vote-depl-svc
                port:
                  number: 80
