apiVersion: v1
kind: Namespace
metadata:
  name: voting-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-depl
  name: vote-depl
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
        - image: ahmedavid/voting-vote:2100
          name: vote-container
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: vote-depl-svc
  namespace: voting-app
spec:
  type: ClusterIP
  selector:
    app: vote-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-ingress
  namespace: voting-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: vote.test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vote-depl-svc
                port:
                  number: 80
