apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker-depl
  name: worker-depl
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
        - image: ahmedavid/voting-worker:latest
          imagePullPolicy: Always
          name: worker-container
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
